from cryptography.hazmat.backends.interfaces import HashBackend

class HashAlgorithm:
    digest_size: int
    name: str

class SHA1(HashAlgorithm): ...
class SHA256(HashAlgorithm): ...
class SHA384(HashAlgorithm): ...
class SHA512(HashAlgorithm): ...

class Hash:
    def __init__(self, algorithm: HashAlgorithm, backend: HashBackend): ...
    def copy(self) -> Hash: ...
    def finalize(self) -> bytes: ...
    def update(self, data: bytes) -> None: ...
