class AEAD:
    def __init__(self, cipher_name: bytes, key: bytes): ...
    def decrypt(self, nonce: bytes, data: bytes, associated_data: bytes) -> bytes: ...
    def encrypt(self, nonce: bytes, data: bytes, associated_data: bytes) -> bytes: ...

class CryptoError(ValueError): ...

class HeaderProtection:
    def __init__(self, cipher_name: bytes, key: bytes): ...
    def mask(self, sample: bytes) -> bytes: ...
