version: 2

build:
  apt_packages:
    - libopus-dev
    - libvpx-dev
  os: ubuntu-22.04
  tools:
    python: "3.11"

formats:
  - pdf

python:
  version: 3.7
  install:
    - requirements: requirements/doc.txt
    - method: pip
      path: .
