version: 2

build:
  apt_packages:
    - libopus-dev
    - libvpx-dev
  os: ubuntu-22.04
  tools:
    python: "3.11"

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
    - requirements: requirements/doc.txt

sphinx:
  configuration: docs/conf.py
