#!/bin/sh

set -e

if [ "$BUILD" = "sdist" ]; then
    python3 setup.py sdist
    if [ -n "$TRAVIS_TAG" ]; then
        pip3 install twine
        python3 -m twine upload --skip-existing dist/*
    fi
else
    flake8 aiortc examples tests
    isort -c -df -rc aiortc examples tests
    coverage run setup.py test
    curl -s https://codecov.io/bash | bash
fi
