#!/bin/sh

set -e

destdir=$1
cachedir=$1.$PYTHON_ARCH
tmpdir=$1.tmp

for d in libvpx opus $destdir $tmpdir; do
    if [ -e $d ]; then
        rm -rf $d
    fi
done

if [ ! -e $cachedir ]; then
    # build libvpx
    mkdir libvpx
    curl -L https://github.com/webmproject/libvpx/archive/v1.8.2.tar.gz | tar xz -C libvpx --strip-components 1
    cd libvpx

    ./configure --prefix=$destdir --disable-examples --disable-tools --disable-unit-tests --enable-pic
    make -j
    make install DESTDIR=$tmpdir
    cd ..

    # build opus
    mkdir opus
    curl https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz | tar xz -C opus --strip-components 1
    cd opus

    ./configure --prefix=$destdir --disable-shared --enable-static --with-pic
    make -j
    make install DESTDIR=$tmpdir

    mv $tmpdir$destdir $cachedir
    rm -rf $tmpdir
fi

cp -R $cachedir $destdir
